export const project = [
  {
    title: "Learnium",
    subtitle:
      "an AI-Powered mobile app in edTech industry. Learnium simplifies the learning process by transforming textbooks into interactive content, provides a flexible learning schedule, and keeps learners engaged in practice and tests by rewarding their progress.",
    description: [
      "🙏🏻 I'm so thankful for my team. We won the Langara College Web & Mobile App Development Capstone presentation!",
      "I'm thrilled to announce that Learnium, the mobile application we've poured our hearts and skills into, has won Langara College's Web & Mobile App Development Capstone presentation! 🎉🥇",
      "Learnium, helps students learn better by turning passive content into interactive experiences with generative AI technology. This idea came from my own personal struggle with reading a book. I found that I learned new topics better when it was interactive, like taking quizzes and memorizing terms with flashcards, compared to just reading alone.",
      "Over the past three months, as the project manager and full-stack developer, I've had an incredible journey of learning and growth. We dove into various technologies - React Native for our front end, Node.js with Express for the backend, and integrating OpenAI API with LangChain to craft our own vector database. This allowed us to convert books into dynamic, interactive experiences, including flashcards and quizzes. Plus, Learnium breaking down complex content into digestible topics and generating personalized study schedules based on exam dates has made learning more effective.",
      "This success wouldn't have been possible without the fantastic minds and dedication of our designers and developers - Nahla Niavarani, Pablo Montoya Varela, Vaibhav Malhotra, Wakana Kaneiwa, Mario Cesena, Edgar Velandia, and Ievgeniia (Genia) Chornobai. Working alongside such talented people like you has been an absolute pleasure.",

      "Explore Learnium. Check it out at https://www.learnium.app",

      "I want to extend gratitude to Tyler Higgs, our exceptional instructor this semester, and all my past instructors at Langara College. Their guidance and imparted knowledge have prepared me for the journey ahead as a developer.",

      "#Learnium #LangaraCollege #WebDevelopment #MobileAppDevelopment #EdTech #LearningJourney",
    ],
    imageMain: `/projects/learnium/heroLearnium.png`,
    link: "https://www.learnium.app/",
    imageArticle: [
      "/projects/learnium/feature1.webp",
      "/projects/learnium/feature2.webp",
      "/projects/learnium/feature3.webp",
      "/projects/learnium/feature4.webp",
      "/projects/learnium/feature5.webp",
    ],
    projectType: "Mobile App",
    projectRole: "Full Stack Developer/Project Manager",
    year: "Dec 2023",
    tool: "React Native, NodeJS, OpenAI API, LangChain, MongoDB, AWS, JWT Token",
  },
  {
    title: "second",
    subtitle:
      "an AI-Powered mobile app in edTech industry. Learnium simplifies the learning process by transforming textbooks into interactive content, provides a flexible learning schedule, and keeps learners engaged in practice and tests by rewarding their progress.",
    description: [
      "Feature #1 Interactive Content",
      "Learnium simplifies interactive content creation by allowing users to upload PDFs, paste text, or capture book pages via OCR technology. It scans and generates key topics for focused learning, including quizzes, flashcards, and summaries.",
      "Feature #2 Dynamic Study Planner",
      "Learnium tailors study sessions to user’s learning preferences and upcoming exam dates. The study plan is responsive to the learner’s progress and quiz results and covers everything that the learner needs to practice to achieve a certain result.",
    ],
    imageMain: "/projects/learnium/feature2.webp",
    link: "https://www.learnium.app/",
    imageArticle: [
      "/projects/learnium/feature1.webp",
      "/projects/learnium/feature2.webp",
      "/projects/learnium/feature3.webp",
      "/projects/learnium/feature4.webp",
      "/projects/learnium/feature5.webp",
    ],
    projectType: "Mobile App",
    projectRole: "Full Stack Developer/Project Manager",
    year: "Dec 2023",
    tool: "React Native, NodeJS, OpenAI API, LangChain, MongoDB, AWS, JWT Token",
  },
  {
    title: "second",
    subtitle:
      "an AI-Powered mobile app in edTech industry. Learnium simplifies the learning process by transforming textbooks into interactive content, provides a flexible learning schedule, and keeps learners engaged in practice and tests by rewarding their progress.",
    description: [
      "Feature #1 Interactive Content",
      "Learnium simplifies interactive content creation by allowing users to upload PDFs, paste text, or capture book pages via OCR technology. It scans and generates key topics for focused learning, including quizzes, flashcards, and summaries.",
      "Feature #2 Dynamic Study Planner",
      "Learnium tailors study sessions to user’s learning preferences and upcoming exam dates. The study plan is responsive to the learner’s progress and quiz results and covers everything that the learner needs to practice to achieve a certain result.",
    ],
    imageMain: "/projects/learnium/feature3.webp",
    link: "https://www.learnium.app/",
    imageArticle: [
      "/projects/learnium/feature1.webp",
      "/projects/learnium/feature2.webp",
      "/projects/learnium/feature3.webp",
      "/projects/learnium/feature4.webp",
      "/projects/learnium/feature5.webp",
    ],
    projectType: "Mobile App",
    projectRole: "Full Stack Developer/Project Manager",
    year: "Dec 2023",
    tool: "React Native, NodeJS, OpenAI API, LangChain, MongoDB, AWS, JWT Token",
  },
  {
    title: "second",
    subtitle:
      "an AI-Powered mobile app in edTech industry. Learnium simplifies the learning process by transforming textbooks into interactive content, provides a flexible learning schedule, and keeps learners engaged in practice and tests by rewarding their progress.",
    description: [
      "Feature #1 Interactive Content",
      "Learnium simplifies interactive content creation by allowing users to upload PDFs, paste text, or capture book pages via OCR technology. It scans and generates key topics for focused learning, including quizzes, flashcards, and summaries.",
      "Feature #2 Dynamic Study Planner",
      "Learnium tailors study sessions to user’s learning preferences and upcoming exam dates. The study plan is responsive to the learner’s progress and quiz results and covers everything that the learner needs to practice to achieve a certain result.",
    ],
    imageMain: "/projects/learnium/feature2.webp",
    link: "https://www.learnium.app/",
    imageArticle: [
      "/projects/learnium/feature1.webp",
      "/projects/learnium/feature2.webp",
      "/projects/learnium/feature3.webp",
      "/projects/learnium/feature4.webp",
      "/projects/learnium/feature5.webp",
    ],
    projectType: "Mobile App",
    projectRole: "Full Stack Developer/Project Manager",
    year: "Dec 2023",
    tool: "React Native, NodeJS, OpenAI API, LangChain, MongoDB, AWS, JWT Token",
  },
  {
    title: "second",
    subtitle:
      "an AI-Powered mobile app in edTech industry. Learnium simplifies the learning process by transforming textbooks into interactive content, provides a flexible learning schedule, and keeps learners engaged in practice and tests by rewarding their progress.",
    description: [
      "Feature #1 Interactive Content",
      "Learnium simplifies interactive content creation by allowing users to upload PDFs, paste text, or capture book pages via OCR technology. It scans and generates key topics for focused learning, including quizzes, flashcards, and summaries.",
      "Feature #2 Dynamic Study Planner",
      "Learnium tailors study sessions to user’s learning preferences and upcoming exam dates. The study plan is responsive to the learner’s progress and quiz results and covers everything that the learner needs to practice to achieve a certain result.",
    ],
    imageMain: "/projects/learnium/feature4.webp",
    link: "https://www.learnium.app/",
    imageArticle: [
      "/projects/learnium/feature1.png",
      "/projects/learnium/feature2.png",
      "/projects/learnium/feature3.png",
      "/projects/learnium/feature4.png",
      "/projects/learnium/feature5.png",
    ],
    projectType: "Mobile App",
    projectRole: "Full Stack Developer/Project Manager",
    year: "Dec 2023",
    tool: "React Native, NodeJS, OpenAI API, LangChain, MongoDB, AWS, JWT Token",
  },
  {
    title: "second",
    subtitle:
      "an AI-Powered mobile app in edTech industry. Learnium simplifies the learning process by transforming textbooks into interactive content, provides a flexible learning schedule, and keeps learners engaged in practice and tests by rewarding their progress.",
    description: [
      "Feature #1 Interactive Content",
      "Learnium simplifies interactive content creation by allowing users to upload PDFs, paste text, or capture book pages via OCR technology. It scans and generates key topics for focused learning, including quizzes, flashcards, and summaries.",
      "Feature #2 Dynamic Study Planner",
      "Learnium tailors study sessions to user’s learning preferences and upcoming exam dates. The study plan is responsive to the learner’s progress and quiz results and covers everything that the learner needs to practice to achieve a certain result.",
    ],
    imageMain: "/projects/learnium/feature2.webp",
    link: "https://www.learnium.app/",
    imageArticle: [
      "/projects/learnium/feature1.png",
      "/projects/learnium/feature2.png",
      "/projects/learnium/feature3.png",
      "/projects/learnium/feature4.png",
      "/projects/learnium/feature5.png",
    ],
    projectType: "Mobile App",
    projectRole: "Full Stack Developer/Project Manager",
    year: "Dec 2023",
    tool: "React Native, NodeJS, OpenAI API, LangChain, MongoDB, AWS, JWT Token",
  },
  {
    title: "second",
    subtitle:
      "an AI-Powered mobile app in edTech industry. Learnium simplifies the learning process by transforming textbooks into interactive content, provides a flexible learning schedule, and keeps learners engaged in practice and tests by rewarding their progress.",
    description: [
      "Feature #1 Interactive Content",
      "Learnium simplifies interactive content creation by allowing users to upload PDFs, paste text, or capture book pages via OCR technology. It scans and generates key topics for focused learning, including quizzes, flashcards, and summaries.",
      "Feature #2 Dynamic Study Planner",
      "Learnium tailors study sessions to user’s learning preferences and upcoming exam dates. The study plan is responsive to the learner’s progress and quiz results and covers everything that the learner needs to practice to achieve a certain result.",
    ],
    imageMain: "/projects/learnium/feature5.webp",
    link: "https://www.learnium.app/",
    imageArticle: [
      "/projects/learnium/feature1.png",
      "/projects/learnium/feature2.png",
      "/projects/learnium/feature3.png",
      "/projects/learnium/feature4.png",
      "/projects/learnium/feature5.png",
    ],
    projectType: "Mobile App",
    projectRole: "Full Stack Developer/Project Manager",
    year: "Dec 2023",
    tool: "React Native, NodeJS, OpenAI API, LangChain, MongoDB, AWS, JWT Token",
  },
];
